app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
	return View::make('welcome');
    return redirect()->route('khatma.show' , [1]);
});


Route::resource('khatma' , 'KhatmatController');
Route::controller('participants' , 'ParticipantsController' , [
	'getParticipate'  => 'get.participate',
	'postParticipate' => 'post.participate',
	'getFinish'       => 'get.finish',
]);

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/KhatmatController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\View;
use Khatma\Khatma\Commands\AddKhatmaCommand;
use Khatma\Khatma\Khatma;
use Khatma\Khatma\KhatmaRepository;
use Khatma\Transformers\KhatmaTransformer;
use Khatma\User\UserRepository;
use Laracasts\Commander\CommanderTrait;

class KhatmatController extends Controller
{
	use CommanderTrait;


	/**
	 * Khatma repository instance.
	 *  
	 * @var Khatma\Khatma\KhatmaRepository
	 */
	private $khatma_repository;


	/**
	 * User repository instance.
	 * 
	 * @var Khatma\User\UserRepository
	 */
	private $user_repository;


	/**
	 * Khatma Transformer instance.
	 * 
	 * @var Khatma\Transformers\KhatmaTransformer
	 */
	private $khatma_transformer;


	public function __construct(KhatmaRepository $khatma_repository, KhatmaTransformer $khatma_transformer, UserRepository $user_repository)
	{
		$this->khatma_repository = $khatma_repository;
		$this->khatma_transformer = $khatma_transformer;
		$this->user_repository = $user_repository;
	}


	/**
	 * List all the unfinshed khatmat.
	 */
    public function index()
    {
    	$khatmat         = $this->khatma_repository->getUnFinishedKhatmat();
    	$data['khatmat'] = $this->khatma_transformer->transformCollection($khatmat);

        return View::make('Khatma.index', $data);
    }


    public function show($id)
    {
    	$khatma = $this->khatma_repository->find_by_id($id);
    	$data['khatma'] = $this->khatma_transformer->transform($khatma);

    	return View::make('Khatma.khatma' , $data);
    }

    /**
     * Creat khatma form page.
     */
    public function create()
    {
    	return View::make('Khatma.create');
    }


    /**
     * Add new khatma.
     */
    public function store()
    {
    	$user_id = $this->user_repository->getRandomUserId();
    	Input::merge(['user_id' => $user_id]); // Random user id 

    	$validator = Validator::make(Input::all() , Khatma::$rules);
    	if ($validator->fails()){ return $validator->messages(); }

    	$this->execute(AddKhatmaCommand::class);

    	return Redirect::route('khatma.index');
    }

}

app/Http/Controllers/ParticipantsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\View;
use Khatma\Participant\Commands\FinishGoz2Command;
use Khatma\Participant\Commands\ParticipateCommand;
use Khatma\Participant\Participant;
use Khatma\Participant\ParticipantRepository;
use Laracasts\Commander\CommanderTrait;

class ParticipantsController extends Controller
{

	use CommanderTrait;


	/**
	 * Participant repository instance.
	 * 
	 * @var Khatma\Participant\ParticipantRepository
	 */
	private $participant_repository;


	public function __construct(ParticipantRepository $participant_repository)
	{
		$this->participant_repository = $participant_repository;
	}
	

	/**
	 * Page where the visitor can participate to a khatma.
	 */
	public function getParticipate($khatma_id , $goz2)
	{
		$data['khatma_id'] = $khatma_id;
    	$data['goz2'] 	   = $goz2;

    	return View::make('Participants.participate' , $data);
	}


	/**
	 * Handle the participation request.
	 */
	public function postParticipate($khatma_id , $goz2)
	{
		Input::merge(['khatma_id' => $khatma_id , 'goz2' => $goz2]);

    	$validator = Validator::make(Input::all() , Participant::$rules);
    	if ($validator->fails()){ return $validator->messages(); }

		$this->execute(ParticipateCommand::class);

		return Redirect::route('khatma.show', [$khatma_id]);
	}


	/**
	 * Handle finishing goz2 request.
	 */
	public function getFinish($khatma_id , $goz2)
	{
		if (! $this->participant_repository->allowed($khatma_id , $goz2)){ return "You are not allowed to finish this Goz2"; }

		Input::merge(['khatma_id' => $khatma_id , 'goz2' => $goz2]);

		$this->execute(FinishGoz2Command::class);

		return Redirect::route('khatma.show', [$khatma_id]);
	}
}

resources/views/Khatma/create.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Create Khatma</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
	<div class="container">
		<h3> Create New Khatma </h3>
		<form method="POST" action="{{ URL::route('khatma.store') }}" class="form-horizontal">
				<input type="hidden" name="_token" value="{{ csrf_token() }}">
			<div class="form-group">
				<label> Name of Khatma : </label>
				<input type="text" name="name" class="form-control" placeholder="name"/>
			</div>
			<div class="form-group">
				<input type="submit" value="Add" class="btn btn-primary"/>	
			</div>
		</form>
	</div>
</body>
</html>

resources/views/Khatma/index.blade.php
<!DOCTYPE html>
<html>
<head>
	<title> Khatma </title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>

	<table class="table table-striped table-bordered">
		<tr>
			<th> Name </th>
			<th> Owner </th>
			<th> Finished </th>
			<th> Added </th>
		</tr>
		@foreach($khatmat as $khatma)
			<tr>
				<td> <a href="{{ URL::route('khatma.show' , [$khatma['id']]) }}"> {{ $khatma['name'] }} </a> </td>
				<td> {{ $khatma['owner'] }} </td>
				<td> {{ $khatma['finished'] }} / 30 </td>
				<td> {{ $khatma['added'] }} </td>
			</tr>
		@endforeach
	</table>

</body>
</html>

resources/views/Khatma/khatma.blade.php
<!DOCTYPE html>
<html>
<head>
	<title> Khatma </title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
	<p> Name  :  {{ $khatma['name'] }} </p>
	<p> Owner :  {{ $khatma['owner'] }} </p>
	<p> Added :  {{ $khatma['added'] }} </p>
	<table class="table table-striped table-bordered">
		<tr>
			<th> # </th>
			<th> Name </th>
			<th> Status </th>
			<th> Action </th>
		</tr>
		@foreach($khatma['participants'] as $participant)
			<tr>
				<td> {{ $participant['goz2'] }} </td>
				<td> {{ $participant['name'] }} </td>
				<td> {{ getGoz2Status($participant['status']) }} </td>
				<td> 
					@if ($participant['status'] == 0) 
						<a class="btn btn-primary btn-xs" href="{{ URL::route('get.participate' , [ $khatma['id'] , $participant['goz2']  ]) }}"> Participate </a>
					@elseif($participant['status'] == 1)
						<a class="btn btn-success btn-xs" href="{{ URL::route('get.finish' , [ $khatma['id'] , $participant['goz2']  ]) }}"> Fininsh </a>
					@else
						<a class="btn btn-warning btn-xs disabled">Finished</a>
					@endif
				</td>
			</tr>
		@endforeach
	</table>

	<script type="text/javascript">

	</script>
</body>
</html>

resources/views/Participants/participate.blade.php
<!DOCTYPE html>
<html>
<head>
	<title> Participate </title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
	<div class="container">
		<h3> Participate by reading Goz2 #{{ $goz2 }} </h3>
		<form method="POST" action="{{ URL::route('post.participate' , [$khatma_id , $goz2]) }}" class="form-horizontal">
			<input type="hidden" name="_token" value="{{ csrf_token() }}">
			 	<div class="form-group">
				    <label> Name </label>
				    <input type="text" name="name" class="form-control" placeholder="Name">
			 	</div>
				<div class="form-group">
			    	<label> Email address </label>
			    	<input type="email" name="email" class="form-control" placeholder="Email">
			 	</div>
				<div class="form-group">
					<input class="btn btn-primary" type="submit" value="Participate" />	
				</div>
		</form>
	</div>

</body>
</html>